# Generated by Django 2.1.7 on 2023-04-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20190310_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='price',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='vat',
        ),
    ]
