version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.7
        commands: 
            - pip install --upgrade pip
            - python3 -m venv myvenv
            - chmod +x ./myvenv/bin/activate
            # Install dependencies needed for running the static analysis
            - pip install -r requirements.txt pylint
            - pip install -r requirements.txt
    pre_build:
        commands:
            - python --version
            - pylint $CODEBUILD_SRC_DIR/*.py
            - pylint $CODEBUILD_SRC_DIR/cookingv2/*.py > report.json
            - cat report.json
            
    build:
        commands:
            - python manage.py migrate
artifacts:
    files:
        - '**/*'
