version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install --upgrade pip
      - python3 -m venv myvenv
      - chmod +x ./myvenv/bin/activate
      - pip install -r requirements.txt pylint
      - pip install -r requirements.txt
  pre_build:
    commands:
      - python --version
      - pylint $CODEBUILD_SRC_DIR/*.py
      - >-
        pylint --output-format=json  $CODEBUILD_SRC_DIR/cookingv2/*.py >
        report.json
      - cat report.json
  build:
    commands:
      - python manage.py migrate
artifacts:
  files:
    - '**/*'
